# Generated by Django 5.2.13 on 2026-04-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
